// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <openenclave/host.h>
#include <stdio.h>

// Include the untrusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool sgx_edger8r against the helloworld.edl file.
#include "helloworld_u.h"

// This is the function that the enclave will call back into to
// print a message.
int host_helloworld(void)
{
    return fprintf(stdout, "Enclave called into host to print: Hello World!\n");
}

int main(int argc, const char* argv[])
{
    oe_result_t result;
    int ret = 1;
    oe_enclave_t* enclave = NULL;
    uint32_t enclave_flags = 0;
    uint8_t* report_buffer = NULL;
    size_t report_buffer_size;
    oe_report_t parsed_report = {0};

    if (argc != 2)
    {
        fprintf(stderr, "Usage: %s enclave_image_path\n", argv[0]);
        goto exit;
    }

    // Create the enclave
#ifdef _DEBUG
    enclave_flags |= OE_ENCLAVE_FLAG_DEBUG;
#endif
    result = oe_create_helloworld_enclave(
        argv[1], OE_ENCLAVE_TYPE_UNDEFINED, enclave_flags, NULL, 0, &enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_create_enclave(): result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    // Call into the enclave
    int hostResult;
    result = enclave_helloworld(enclave, &hostResult);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into enclave_helloworld failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }
    if (hostResult != OE_OK)
    {
        fprintf(stderr, "OCALL failed: result=%u\n", hostResult);
        goto exit;
    }

    result = oe_get_report_v2(enclave, 0, NULL, 0, &report_buffer, &report_buffer_size);
    if (result != OE_OK)
    {
        fprintf(stderr, "Failed to obtain enclave report: result=%u\n", result);
        goto exit;
    }

    result = oe_parse_report(report_buffer, report_buffer_size, &parsed_report);
    if (result != OE_OK)
    {
        fprintf(stderr, "Failed to parse enclave report: result=%u\n", result);
        goto exit;
    }

    const char *enclaveType;
    switch (parsed_report.type)
    {
        case OE_ENCLAVE_TYPE_UNDEFINED:
            enclaveType = "Undefined";
            break;

        case OE_ENCLAVE_TYPE_SGX:
            enclaveType = "SGX";
            break;

        case OE_ENCLAVE_TYPE_TRUSTZONE:
            enclaveType = "TrustZone";
            break;

        default:
            enclaveType = "Unknown";
            break;
    }

    printf("Enclave Attestation Report:\n");
    printf("\tType: %s\n", enclaveType);
    printf("\tID Version: %d\n", parsed_report.identity.id_version);
    printf("\tSecurity Version: %d\n", parsed_report.identity.security_version);
    printf("\tAttributes: 0x%llx\n", parsed_report.identity.attributes);
    printf("\tProduct ID: ");
    for (int i = 0; i < sizeof(parsed_report.identity.product_id); i++)
    {
        printf("%02x", parsed_report.identity.product_id[i]);
    }
    putchar('\n');
    printf("\tUnique ID: ");
    for (int i = 0; i < sizeof(parsed_report.identity.unique_id); i++)
    {
        printf("%02x", parsed_report.identity.unique_id[i]);
    }
    putchar('\n');
    printf("\tSigner ID: ");
    for (int i = 0; i < sizeof(parsed_report.identity.signer_id); i++)
    {
        printf("%02x", parsed_report.identity.signer_id[i]);
    }
    putchar('\n');

    printf("\tDevice Unique ID: ");
    for (int i = 0; i < sizeof(parsed_report.identity.device_unique_id); i++)
    {
        printf("%02x", parsed_report.identity.device_unique_id[i]);
    }
    putchar('\n');
    printf("\tDevice Signer ID: ");
    for (int i = 0; i < sizeof(parsed_report.identity.device_signer_id); i++)
    {
        printf("%02x", parsed_report.identity.device_signer_id[i]);
    }
    putchar('\n');

    ret = 0;

exit:
    if (report_buffer)
        oe_free_report(report_buffer);

    // Clean up the enclave if we created one
    if (enclave)
        oe_terminate_enclave(enclave);

    return ret;
}
